#!/bin/sh

#define the $USER variable based on the logged in user
logged_in_user=$USER

#add logged in user to admin group
sudo dseditgroup -o edit -a "$logged_in_user" -t user admin

#verify that the user has been added to the admin group then finish
if dseditgroup -o checkmember -m "$logged_in_user" admin | grep -q "yes"; then

#finish	
	fi
