#!/bin/bash
# Notifies user if screenshare is enabled.  Specifically for use with Addigy MDM but can be tailored to others.

# Adjust these variables as they will replace the text in the flags

title="Screen Sharing Request"
description="An Administrator is requesting access to remotely access your computer.  If you were not made aware of this session, please notify your Admin"
acceptText="Accept"
closeText="Close"
timeOut=600
forefront="False"

if /Library/Addigy/macmanage/MacManage.app/Contents/MacOS/MacManage action=notify title="${title}" description="${description}" closeLabel="${closeText}" acceptLabel="${acceptText}" timeout="$timeOut" forefront="$forefront"; then
    # executes a desired command if the user clicks the Accept label.
    echo "Accept label clicked"
    exit 0
else
    # executes a desired command if the user clicks the Close label.
    echo "Close label clicked"
    exit 1
fi#!/bin/bash
