#!/bin/sh

# Get the logged-in username
logged_in_user=$USER

# Check if the user is in the admin group
if dseditgroup -o checkmember -m "$logged_in_user" admin | grep -q "yes"; then

  # Remove the user from the admin group
  sudo dseditgroup -o edit -d "$logged_in_user" -t user admin;

  # check to make sure user is removed from the admin group  
if dseditgroup -o checkmember -m "$logged_in_user" admin | grep -q "no"

  #finish it up 
fi
